apiVersion: v2
name: profiler
description: Deploy zymtrace's profiler agent
type: application
version: 25.12.6
appVersion: "25.12.6"
icon: https://helm.zystem.io/zymtrace-logo-255x255.png
keywords:
  - zymtrace
  - profiler
  - observability
  - GPU
  - CPU
  - agent
home: https://docs.zymtrace.com
sources:
  - https://github.com/zystem-io/zymtrace-charts/
