apiVersion: v2
name: profiler
description: Deploy zymtrace's profiler agent
type: application
version: 25.12.2
appVersion: "25.12.2"
keywords:
  - zymtrace
  - profiler
  - observability
  - GPU
  - CPU
  - agent
home: https://docs.zymtrace.com
sources:
  - https://github.com/zystem-io/deploy-zymtrace
