apiVersion: v2
name: backend
description: Deploy zymtrace's self-hosted services
type: application
version: 26.2.5
appVersion: "26.2.5"
icon: https://helm.zystem.io/zymtrace-logo-255x255.png
keywords:
  - zymtrace
  - profiler
  - observability
  - GPU
  - CPU
home: https://docs.zymtrace.com
sources:
  - https://github.com/zystem-io/zymtrace-charts/
