apiVersion: v2
name: backend
description: Deploy zymtrace's self-hosted services
type: application
version: 25.11.0
appVersion: "25.11.0"
keywords:
  - zymtrace
  - profiler
  - observability
  - GPU
  - CPU
home: https://docs.zymtrace.com
sources:
  - https://github.com/zystem-io/deploy-zymtrace
