apiVersion: v2
name: backend
description: Deploy zymtrace's self-hosted services
type: application
version: 25.12.5
appVersion: "25.12.5"
keywords:
  - zymtrace
  - profiler
  - observability
  - GPU
  - CPU
home: https://docs.zymtrace.com
sources:
  - https://github.com/zystem-io/zymtrace-charts/
annotations:
  artifacthub.io/logoURL: https://helm.zystem.io/zymtrace-logo-255x255.png
